spring.application.name=springAI


spring.ai.openai.api-key = lm-studio
spring.ai.openai.base-url = http://127.0.0.1:1234/v1
spring.ai.openai.chat.options.model = phi-3-mini-4k-instruct
spring.ai.openai.chat.options.max-tokens=2048
spring.ai.openai.timeout=300s

spring.datasource.url=jdbc:postgresql://localhost:5432/springboot
spring.datasource.username=postgres
spring.datasource.password=Navaneethveer
spring.jpa.hibernate.ddl-auto=update


spring.ai.chat.memory.repository.jdbc.initialize-schema=ALWAYS